#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function gem_cleanup() {
  EXCLUDE_SYSTEM_GEMS="true" "${DIR}/bundle/bin/bundle-env" gem cleanup
}

if [ "$1" = "update_fastlane" ]; then
  "${DIR}/bundle/bin/bundle-env" gem update fastlane pilot spaceship produce deliver frameit pem snapshot screengrab supply cert sigh match scan gym fastlane_core credentials_manager
  gem_cleanup
else
  exec "${DIR}/bundle/bin/bundle-env" fastlane "$@"
fi;
