#!/bin/bash
BIN=$(cd "$(dirname "$0")"; pwd)
PREFIX=$(dirname $BIN)
LIB_PATH=$(dirname $PREFIX)

# Clear known env variables that can influence the standalone installation in a bad way.
unset RUBYOPT
unset RUBYLIB
unset GEM_HOME
unset GEM_PATH
unset GEM_CACHE

# Now define env variables that we need for the standalone installation to work and override where
# necessary.

export PATH=$BIN:$PATH
export SSL_CERT_FILE=$PREFIX/share/cacert.pem

export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Tell Ruby where to find the gems
export GEM_PATH=$LIB_PATH/bundle/bin

# Suppress errors relating to native extensions in the user's gemset.
exec "$@" 2> >(grep -v '^Ignoring .* because its extensions are not built.  Try: gem pristine .* --version .*')
