#!/bin/bash
FASTLANE_DIR=~/.fastlane/bin

read -p "Do you want to uninstall fastlane from $FASTLANE_DIR? (y/n) " -n 1 choice
echo ""
case "$choice" in
y|Y ) 
  rm -rf "$FASTLANE_DIR"
  echo "Fastlane was uninstalled successfully!"
;;
* )
  echo "Cancelled uninstall process"
  exit 1
;;
esac
