#!/bin/bash
FASTLANE_DIR=~/.fastlane/bin

usage() {
  echo "./uninstall [-y]"
  echo "    -y : Confirm uninstallation, don't ask interactively"
  exit 1
}

while getopts ":y" opt; do
  case $opt in
    y ) UNINSTALL_CONFIRMED=1;;
    * ) usage ;;
  esac
done

if [ "$UNINSTALL_CONFIRMED" == "1" ]; then
  choice="y"
else
  read -p "Do you want to uninstall fastlane from $FASTLANE_DIR? (y/n) " -n 1 choice
  echo ""
fi

case "$choice" in
y|Y ) 
  rm -rf "$FASTLANE_DIR"
  echo "Fastlane was uninstalled successfully!"
;;
* )
  echo "Cancelled uninstall process"
  exit 1
;;
esac
