#!/bin/bash

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$CURRENT_DIR/common.sh"

usage() {
  echo "./uninstall [-y]"
  echo "    -y : Confirm uninstallation, don't ask interactively"
  exit 1
}

while getopts ":y" opt; do
  case $opt in
    y ) UNINSTALL_CONFIRMED=1;;
    * ) usage ;;
  esac
done

if [ "$UNINSTALL_CONFIRMED" == "1" ]; then
  choice="y"
else
  set_color yellow
  read -p "Do you want to uninstall fastlane from $FASTLANE_DIR? (y/n) " -n 1 choice
  echo ""
  reset_color
fi

case "$choice" in
y|Y )
  rm -rf "$FASTLANE_DIR"
  echoc "You can now remove fastlane from your search path by editing your $profile file." yellow
  echoc "fastlane was uninstalled successfully!" green
;;
* )
  echoc "Cancelled uninstall process" red
  exit 1
;;
esac
