version: 2

jobs:
  "Execute install on macOS (Xcode 11.2.0)":
    macos:
      xcode: "11.2.0"
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-homebrew-{{ epoch }}
            - v3-homebrew
      - run: echo 'chruby ruby-2.6' >> ~/.bash_profile
      - run: brew install ruby@2.5
      - run: ./install ~/.fastlane
      - run: ~/.fastlane/bin/fastlane --version
      - save_cache:
          key: v3-homebrew-{{ epoch }}
          paths:
            - /usr/local/Homebrew
  "Excute install on Ubuntu":
    docker:
      - image: circleci/ruby:2.5
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      TERM: dumb
    steps:
      - checkout
      - run: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"  </dev/null && PATH="$HOME/.linuxbrew/bin:$PATH"
      - run: brew install ruby@2.5
      - run: ./install ~/.fastlane
      - run: ~/.fastlane/bin/fastlane --version

workflows:
  version: 2
  build:
    jobs:
      - "Execute install on macOS (Xcode 11.2.0)"
      - "Excute install on Ubuntu"